# Generated by Django 5.0.1 on 2024-03-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_alter_cartdetail_quantity_alter_cartdetail_total'),
        ('products', '0002_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='orders.order'),
        ),
    ]
